# 配置文件

###
### [display]
### 
### 画面配置
###
[display]
  # 画面输出最大行数
  maxRows = 40 

###
### [exchange]
### 
### 交易所相关配置
###
[exchange]
  # 初始默认交易所[kucoin/binance/bitbank], 之后可以通过参数变更
  active = "binance"

###
### [arbitrage]
### 
### 三角套利相关配置
###
[arbitrage]
  # 套利监视间隔(秒)
  interval = 1
  # 最小盈利率
  minRateProfit = 1.02
  # 起点
  start = "BTC"
  # 匹配基准
  baseCoins = ["BNB", "ETH", "USDT"]

###
### [rank]
### 排名计算配置
###
[rank]
  # 数据过滤时间，默认15分钟（秒）
  pairTimer = 900000

###
### [trading]
### 交易相关配置
###
[trading]
  # 只有超过 x% 最小盈利率(minimalProfit)的候选人,排队等待交易
  # minQueueRateThreshold = 3
  # 有多少相同机会的阈值
  # minHitsThreshold = 5

###
### [account]
### 账户相关配置
### apiKey与secret在获取行情api中并不是必须项目，只有交易相关api中为必须项目
###
[account]
  # 库币 
  [account.kucoin]
    apiKey = "c"
    secret = "x"

  # binance
  [account.binance]
    # 账号
    apiKey = "zzz"
    secret = "ccc"

  # bitbank
  [account.bitbank]
    # 账号
    apiKey = "1K"
    secret = "f3"